export const faculties = [
  {
    id: "auth-engineering",
    name: "School of Engineering",
    university: "AUTH",
    lat: 40.6331,
    lng: 22.9562,
  },
  {
    id: "auth-sciences",
    name: "School of Sciences",
    university: "AUTH",
    lat: 40.6328,
    lng: 22.9558,
  },
  {
    id: "auth-medicine",
    name: "School of Medicine",
    university: "AUTH",
    lat: 40.6225,
    lng: 22.9568,
  },
  {
    id: "uom-economics",
    name: "School of Economics",
    university: "UoM",
    lat: 40.625,
    lng: 22.961,
  },
  {
    id: "ihu-technology",
    name: "School of Technology",
    university: "IHU",
    lat: 40.6545,
    lng: 22.9347,
  },
];

export const listings = [
  {
    listing_id: "0001-01",
    address: "Tsimiski 45",
    neighborhood: "Kentro",
    monthly_price: 350,
    currency: "EUR",
    bills_included: true,
    deposit: 350,
    property_type: "studio",
    amenities: ["AC", "Furnished", "Elevator", "Balcony"],
    description:
      "Bright studio apartment in the heart of Thessaloniki, walking distance to Aristotelous Square. Fully furnished with modern appliances, air conditioning, and a small balcony overlooking the street.",
    photos: ["/photos/0001-01_1.jpg", "/photos/0001-01_2.jpg"],
    landlord: {
      name: "Dimitris Papadopoulos",
      contact_info: "d.papadopoulos@email.gr",
    },
    faculty_distances: [
      { faculty_name: "AUTH School of Engineering", walk_minutes: 25, transit_minutes: 12 },
      { faculty_name: "AUTH School of Sciences", walk_minutes: 25, transit_minutes: 12 },
      { faculty_name: "AUTH School of Medicine", walk_minutes: 20, transit_minutes: 10 },
      { faculty_name: "UoM School of Economics", walk_minutes: 18, transit_minutes: 8 },
      { faculty_name: "IHU School of Technology", walk_minutes: 45, transit_minutes: 22 },
    ],
  },
  {
    listing_id: "0002-01",
    address: "Vassilissis Olgas 120",
    neighborhood: "Kalamaria",
    monthly_price: 280,
    currency: "EUR",
    bills_included: false,
    deposit: 280,
    property_type: "room",
    amenities: ["AC", "Furnished"],
    description:
      "Private room in a shared 3-bedroom apartment in quiet Kalamaria. Shared kitchen and bathroom. Close to the waterfront promenade. Ideal for students who prefer a calm neighborhood.",
    photos: ["/photos/0002-01_1.jpg"],
    landlord: {
      name: "Maria Konstantinou",
      contact_info: "m.konstantinou@email.gr",
    },
    faculty_distances: [
      { faculty_name: "AUTH School of Engineering", walk_minutes: 40, transit_minutes: 20 },
      { faculty_name: "AUTH School of Sciences", walk_minutes: 40, transit_minutes: 20 },
      { faculty_name: "AUTH School of Medicine", walk_minutes: 30, transit_minutes: 15 },
      { faculty_name: "UoM School of Economics", walk_minutes: 28, transit_minutes: 14 },
      { faculty_name: "IHU School of Technology", walk_minutes: 55, transit_minutes: 30 },
    ],
  },
  {
    listing_id: "0003-01",
    address: "Egnatia 78",
    neighborhood: "Kentro",
    monthly_price: 450,
    currency: "EUR",
    bills_included: true,
    deposit: 450,
    property_type: "1-bedroom",
    amenities: ["AC", "Furnished", "Elevator", "Balcony", "Parking"],
    description:
      "Spacious 1-bedroom apartment on Egnatia street with modern renovation. Open-plan kitchen and living area. Includes a dedicated parking spot in the building garage. Bills included in rent.",
    photos: ["/photos/0003-01_1.jpg", "/photos/0003-01_2.jpg", "/photos/0003-01_3.jpg"],
    landlord: {
      name: "Giorgos Alexiou",
      contact_info: "g.alexiou@email.gr",
    },
    faculty_distances: [
      { faculty_name: "AUTH School of Engineering", walk_minutes: 20, transit_minutes: 10 },
      { faculty_name: "AUTH School of Sciences", walk_minutes: 20, transit_minutes: 10 },
      { faculty_name: "AUTH School of Medicine", walk_minutes: 22, transit_minutes: 11 },
      { faculty_name: "UoM School of Economics", walk_minutes: 22, transit_minutes: 11 },
      { faculty_name: "IHU School of Technology", walk_minutes: 40, transit_minutes: 20 },
    ],
  },
  {
    listing_id: "0003-02",
    address: "Olympou 15",
    neighborhood: "Ano Poli",
    monthly_price: 220,
    currency: "EUR",
    bills_included: false,
    deposit: 220,
    property_type: "room",
    amenities: ["Furnished"],
    description:
      "Cozy room in the upper town with views of the Thermaic Gulf. Shared apartment with one other student. Traditional Thessaloniki architecture. Note: no elevator, ground floor unit.",
    photos: ["/photos/0003-02_1.jpg"],
    landlord: {
      name: "Giorgos Alexiou",
      contact_info: "g.alexiou@email.gr",
    },
    faculty_distances: [
      { faculty_name: "AUTH School of Engineering", walk_minutes: 30, transit_minutes: 18 },
      { faculty_name: "AUTH School of Sciences", walk_minutes: 30, transit_minutes: 18 },
      { faculty_name: "AUTH School of Medicine", walk_minutes: 35, transit_minutes: 20 },
      { faculty_name: "UoM School of Economics", walk_minutes: 35, transit_minutes: 20 },
      { faculty_name: "IHU School of Technology", walk_minutes: 50, transit_minutes: 28 },
    ],
  },
  {
    listing_id: "0004-01",
    address: "Mitropoleos 33",
    neighborhood: "Kentro",
    monthly_price: 520,
    currency: "EUR",
    bills_included: true,
    deposit: 520,
    property_type: "2-bedroom",
    amenities: ["AC", "Furnished", "Elevator", "Balcony"],
    description:
      "Modern 2-bedroom apartment near the White Tower. Perfect for two students sharing. Large living room, fully equipped kitchen, two bathrooms. Quiet building with elevator.",
    photos: ["/photos/0004-01_1.jpg", "/photos/0004-01_2.jpg"],
    landlord: {
      name: "Elena Georgiou",
      contact_info: "e.georgiou@email.gr",
    },
    faculty_distances: [
      { faculty_name: "AUTH School of Engineering", walk_minutes: 28, transit_minutes: 14 },
      { faculty_name: "AUTH School of Sciences", walk_minutes: 28, transit_minutes: 14 },
      { faculty_name: "AUTH School of Medicine", walk_minutes: 15, transit_minutes: 8 },
      { faculty_name: "UoM School of Economics", walk_minutes: 12, transit_minutes: 6 },
      { faculty_name: "IHU School of Technology", walk_minutes: 48, transit_minutes: 25 },
    ],
  },
];
